image: node:latest

variables:

before_script:
    - apk add --no-cache git
    - yarn install --prod

stages:
    - build

compile:
    stage: build
    script:
        - yarn build
    artifacts:
        paths:
            - build/
