image: node:latest

before_script:
    - apk add --no-cache git
    - yarn install --prod

stages:
    - build

cache:
    paths:
        - node_modules/

install_dependencies:
    stage: build
    script:
        - yarn build
    artifacts:
        paths:
            - build/
