image: node:10.9.0-alpine

variables:

before_script:
    - yarn install npm-run-all

stages:
    - build

compile:
    stage: build
    script:
        - yarn build
    artifacts:
        paths:
            - build/
