image: node:latest

cache:
  untracked: true
  key: '$CI_BUILD_REF_NAME'
  paths:
    - node_modules/
    - build/=

before_script:
  - apt-get update -qq && apt-get install

stages:
  - setup
  - build

setup:
  stage: setup
  script:
    - npm install

build:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
      - build/=
    policy: pull
  script:
    - npm run build
  artifacts:
    paths:
      - build/
