image: alpine

variables:

before_script:
    - apk add --no-cache git

stages:
    - build

compile:
    stage: build
    script:
        - bash build.sh
    artifacts:
        paths:
            - build/
