image: node:10.9.0-alpine

variables:
    stages:
        - build

before_script:
    - apk add --no-cache git
    - yarn install --prod

compile:
    stage: build
    script:
        - yarn build
    artifacts:
        paths:
            - build/
