image: node:latest

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - apt-get update -qq && apt-get install
  - yarn config set cache-folder .yarn
  - yarn

stages:
  - build

build:
  stage: build
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
      - .yarn
    policy: pull
  script:
    - yarn build
  artifacts:
    paths:
      - build/
